### ISSUE TITLE
Crashing on Windows with Pidgin 2.14.9

### ISSUE THREAD

**Issue by nxths** [EionRobb/purple-googlechat#45]
I installed the purple-googlechat plugin yesterday following the Windows section of https://github.com/EionRobb/purple-googlechat/blob/master/README.md, have been seeing consistent crashes either:
- immediately at startup
- randomly within a few hours of starting pidgin

Looking at the `debug.log` generated from `pidgin.exe --debug 2>&1 > "%USERPROFILE%\debug.log"`, the last log lines are:
```
(13:15:14) nss: Trusting CN=*.google.com
(13:15:14) certificate: Successfully verified certificate for chat.google.com
(13:15:14) http: Request 0874F000 performed successfully.
(13:15:14) http: Request 0874F498 performed successfully.
(13:15:14) googlechat: Received new other event 058E1C60
(13:15:14) googlechat: {
	"group_id" : null,
	"type" : "SESSION_READY",
	"body" : {
		"group_viewed" : null,
		"message_posted" : null,
		"web_push_notification" : null,
		"event_type" : "SESSION_READY",
		"membership_changed" : null,
		"trace_id" : null,
		"user_status_updated_event" : null,
		"typing_state_changed_event" : null,
		"read_receipt_changed" : null
	},
	"user_id" : null,
	"user_revision" : null,
	"group_revision" : null,
	"bodies" : [
	]
}
(13:15:14) http: Request 0874E8C8 performed successfully.
(13:15:14) http: Performing new request 0874F2A0 to chat.google.com.
(13:15:14) http: Performing new request 0874ED60 to chat.google.com.
```

The last few log lines look the same (always has that json body with nulls) for all crashes I've seen.  Other notes:
- Am running Pidgin 2.14.19 on up-to-date Windows 10 64-bit
- No other plugins are installed or enabled besides the built-in "Release Notification" plugin
- Was previously using pidgin with the same google account except through the built-in gtalk protocol, and wasn't experiencing crashes then
- No other accounts are added in pidgin besides the one google account for gchat

Let me know if any other info is useful, thanks!

**Comment by EionRobb** [comment]
Whoops! Sorry about the crashes. 

Could you follow the instructions at https://developer.pidgin.im/wiki/GetABacktrace to get a backtrace and attach to this issue. Hopefully that points to where the problem is lurking.

**Comment by nxths** [comment]
[pidgin.zip](https://github.com/EionRobb/purple-googlechat/files/8714451/pidgin.zip) this has a pidgin.RPT file from an immediate crash on startup

**Comment by EionRobb** [comment]
Darn, doesn't show much other than something in the plugin is trying to free memory it doesn't have access to.

If it were me trying to debug it'd I'd be running it through gdb using https://developer.pidgin.im/wiki/GetABacktrace#TheEasyWay, but wouldn't want you to jump through that hoop as it's a bit fiddly on windows.

I'll try work out if there's any extra debugging I can add into the plugin that would help track down where its dying.

Just to help rule out something easier to deal with,  can you check what version of glib you've got in Help->Build Information->Glib Runtime?

**Comment by nxths** [comment]
The Build Information window says: `Glib Runtime: 2.28.8`
I'll see if I can get a gdb session through WSL or MinGW, will followup thanks

**Comment by nxths** [comment]
Running gdb in WSL on the pidgin windows binary (installed w/ debug symbols enabled):
```
nxths@computer:/mnt/c/Program Files (x86)/Pidgin$ gdb pidgin.exe 2>&1 | tee ~/pidgin-backtrace.log
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pidgin.exe...
(No debugging symbols found in pidgin.exe)
(gdb) handle SIGPIPE nostop noprint
Signal        Stop      Print   Pass to program Description
SIGPIPE       No        No      Yes             Broken pipe
(gdb) run
Starting program: /mnt/c/Program Files (x86)/Pidgin/pidgin.exe
warning: Selected architecture i386 is not compatible with reported target architecture i386:x86-64
warning: Architecture rejected target-supplied description
Loaded exchndl.dll
 Setting exchndl.dll LogFile to C:\Users\nxths\AppData\Local\Temp\pidgin.RPT
 Setting exchndl.dll DebugInfoDir to C:\Program Files (x86)\Pidgin\pidgin-2.14.9-dbgsym
GTK+ path found: C:\Program Files (x86)\Pidgin\Gtk\bin
Using SetDllDirectory
Setting locale: LANG=en
attempting to load 'C:\Program Files (x86)\Pidgin\pidgin.dll'
Prefix='C:\Program Files (x86)\Pidgin\spellcheck'
Looking for modules in dir='C:\Users\nxths\AppData\Local\enchant'
Looking for modules in dir='C:\Users\nxths\enchant'
Looking for modules in dir='C:\Program Files (x86)\Pidgin\spellcheck\lib\enchant'

(Pidgin:17268): Json-CRITICAL **: json_object_unref: assertion `object != NULL' failed

(Pidgin:17268): Json-CRITICAL **: json_object_unref: assertion `object != NULL' failed
[Inferior 1 (process 16845) exited with code 05]
(gdb) bt full
No stack.
(gdb)
```

I don't know if gdb in WSL actually works on windows binaries (e.g. missing `bt full`).  The messages about unexpected json null seem like it could be related to the `debug.log` output with null fields from earlier.

**Comment by nxths** [comment]
Running gdb with MinGW on the pidgin windows binary, it doesn't recognize the debug symbols but does have `bt full` output:
```
PS C:\Program Files (x86)\Pidgin> gdb pidgin.exe 2>&1 | tee "C:/Users/nxths/Desktop/pidgin-backtrace.log"
GNU gdb (GDB for MinGW-W64 x86_64, built by Brecht Sanders) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pidgin.exe...
(No debugging symbols found in pidgin.exe)
(gdb)
(gdb)
(gdb) handle SIGPIPE nostop noprint
Signal        Stop      Print   Pass to program Description
SIGPIPE       No        No      Yes             Broken pipe
(gdb) run
Starting program: C:\Program Files (x86)\Pidgin\pidgin.exe
[New Thread 12424.0x18bc]
[New Thread 12424.0xb10]
[New Thread 12424.0x1f10]
[New Thread 12424.0x31a0]
[New Thread 12424.0x1f4c]
[Thread 12424.0x1f4c exited with code 0]
[New Thread 12424.0x3640]
[New Thread 12424.0x2a5c]
[New Thread 12424.0x11c0]
[New Thread 12424.0x223c]
[Thread 12424.0x3640 exited with code 0]
[New Thread 12424.0x3d44]
[New Thread 12424.0x1d10]
[New Thread 12424.0x3eec]
Loaded exchndl.dll
 Setting exchndl.dll LogFile to C:\Users\nxths\AppData\Local\Temp\pidgin.RPT
 Setting exchndl.dll DebugInfoDir to C:\Program Files (x86)\Pidgin\pidgin-2.14.9-dbgsym
GTK+ path found: C:\Program Files (x86)\Pidgin\Gtk\bin
Using SetDllDirectory
Setting locale: LANG=en
attempting to load 'C:\Program Files (x86)\Pidgin\pidgin.dll'
Prefix='C:\Program Files (x86)\Pidgin\spellcheck'
Looking for modules in dir='C:\Users\nxths\AppData\Local\enchant'
Looking for modules in dir='C:\Users\nxths\enchant'
Looking for modules in dir='C:\Program Files (x86)\Pidgin\spellcheck\lib\enchant'
[New Thread 12424.0x192c]
[New Thread 12424.0x5628]
[Thread 12424.0x5628 exited with code 0]
[New Thread 12424.0x354c]
[New Thread 12424.0x3578]
[New Thread 12424.0x49c]
[Thread 12424.0x3578 exited with code 0]
[Thread 12424.0x192c exited with code 0]
[New Thread 12424.0x1d34]
[New Thread 12424.0x4a00]
[Thread 12424.0x49c exited with code 0]
[New Thread 12424.0x2f80]
[Thread 12424.0x1d34 exited with code 0]
[New Thread 12424.0x47d4]
[Thread 12424.0x4a00 exited with code 0]
[Thread 12424.0x2f80 exited with code 0]
[Thread 12424.0x47d4 exited with code 0]
[New Thread 12424.0x2a6c]
[Thread 12424.0x2a6c exited with code 0]
[New Thread 12424.0x28c0]
[New Thread 12424.0x552c]
[Thread 12424.0x28c0 exited with code 0]
[New Thread 12424.0x2fd0]
[Thread 12424.0x552c exited with code 0]
[New Thread 12424.0x4880]
[Thread 12424.0x2fd0 exited with code 0]
[New Thread 12424.0x264c]
[New Thread 12424.0x45d8]
[Thread 12424.0x4880 exited with code 0]
[New Thread 12424.0x5688]
[Thread 12424.0x45d8 exited with code 0]
[Thread 12424.0x5688 exited with code 0]
[New Thread 12424.0x2cfc]
[New Thread 12424.0x2cf8]
[New Thread 12424.0x384c]
[Thread 12424.0x2cfc exited with code 0]
[New Thread 12424.0x5058]
[Thread 12424.0x2cf8 exited with code 0]
[New Thread 12424.0x4388]
[Thread 12424.0x384c exited with code 0]
[New Thread 12424.0x3bdc]
[Thread 12424.0x5058 exited with code 0]
[New Thread 12424.0x507c]
[Thread 12424.0x4388 exited with code 0]
[New Thread 12424.0x3d48]
[Thread 12424.0x3bdc exited with code 0]
[Thread 12424.0x264c exited with code 0]
[New Thread 12424.0x56e4]
[Thread 12424.0x3d44 exited with code 0]
[New Thread 12424.0x2f00]
[New Thread 12424.0x2d74]
[Thread 12424.0x56e4 exited with code 0]
[New Thread 12424.0x1600]
[Thread 12424.0x507c exited with code 0]
[New Thread 12424.0x14ac]
[Thread 12424.0x1600 exited with code 0]
[New Thread 12424.0x3bf4]
[Thread 12424.0x3bf4 exited with code 0]
[New Thread 12424.0xc84]
[Thread 12424.0x2d74 exited with code 0]
[Thread 12424.0x3d48 exited with code 0]
[New Thread 12424.0x3f88]
[New Thread 12424.0x4794]
[New Thread 12424.0x3074]
[Thread 12424.0x3f88 exited with code 0]
[Thread 12424.0x3074 exited with code 0]
[New Thread 12424.0x34cc]
[New Thread 12424.0x4d5c]
[Thread 12424.0x34cc exited with code 0]
[New Thread 12424.0x11ec]
[Thread 12424.0x4d5c exited with code 0]
[New Thread 12424.0x356c]
[Thread 12424.0x11ec exited with code 0]
[Thread 12424.0xc84 exited with code 0]
[New Thread 12424.0x55e8]
[Thread 12424.0x55e8 exited with code 0]
[New Thread 12424.0x7c8]
[New Thread 12424.0x48c8]
[Thread 12424.0x7c8 exited with code 0]
[New Thread 12424.0x304]
[Thread 12424.0x48c8 exited with code 0]
[New Thread 12424.0x513c]
[Thread 12424.0x304 exited with code 0]
[Thread 12424.0x4794 exited with code 0]
[Thread 12424.0x513c exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x772275d0 in ntdll!RtlValidateHeap () from C:\Windows\SysWOW64\ntdll.dll
(gdb) bt full
#0  0x772275d0 in ntdll!RtlValidateHeap () from C:\Windows\SysWOW64\ntdll.dll
No symbol table info available.
#1  0x011c0000 in ?? ()
No symbol table info available.
#2  0x772dfa9e in ntdll!RtlRegisterSecureMemoryCacheCallback ()
   from C:\Windows\SysWOW64\ntdll.dll
No symbol table info available.
#3  0x77243d36 in ntdll!RtlGetCurrentServiceSessionId ()
   from C:\Windows\SysWOW64\ntdll.dll
No symbol table info available.
#4  0x07ba3770 in ?? ()
No symbol table info available.
#5  0x772878bd in ntdll!RtlGetNtGlobalFlags ()
   from C:\Windows\SysWOW64\ntdll.dll
No symbol table info available.
#6  0x07ba3768 in ?? ()
No symbol table info available.
#7  0x77243c06 in ntdll!RtlFreeHeap () from C:\Windows\SysWOW64\ntdll.dll
No symbol table info available.
#8  0x76f47379 in msvcrt!free () from C:\Windows\SysWOW64\msvcrt.dll
No symbol table info available.
#9  0x011c0000 in ?? ()
No symbol table info available.
#10 0x03866e31 in googlechat_get_users_information_internal (ha=0x4b874f0,
    user_ids=0x4b6a470,
    callback=0x3866bea <googlechat_got_users_information>, userdata=0x0)
    at googlechat_conversation.c:339
        request = {base = {
            descriptor = 0x387bb00 <get_members_request.descriptor>,
            n_unknown_fields = 0, unknown_fields = 0x0},
          request_header = 0x7ba3a58, n_member_ids = 8,
          member_ids = 0x7ba3770, n_membership_ids = 0, membership_ids = 0x0}
        n_member_ids = 8
        member_ids = 0x7ba3770
        cur = 0x0
        i = 8
#11 0x03866e5f in googlechat_get_users_information (ha=0x4b874f0,
    user_ids=0x4b6a470) at googlechat_conversation.c:345
No locals.
#12 0x038683b0 in googlechat_got_conversation_list (ha=0x4b874f0,
    response=0x4bdb788, user_data=0x0) at googlechat_conversation.c:1037
        i = 15
        unique_user_ids = 0x4b6b150
        unique_user_ids_list = 0x4b6a470
        node = 0x0
        googlechat_group = 0x0
#13 0x03861d20 in googlechat_pblite_request_cb (http_conn=0x4bda718,
    response=0x4bda7d0, user_data=0x4bb0a60) at googlechat_connection.c:578
        safety_encoding = 0x0
        request_info = 0x4bb0a60
        ha = 0x4b874f0
        callback = 0x3867fa2 <googlechat_got_conversation_list>
        real_user_data = 0x0
        response_message = 0x4bb0280
        unpacked_message = 0x4bdb788
        raw_response = 0x7bac018 "\022\fCPmUsIa77PcC\032\t\bƒ▓\200Ü▒σ≈\002\"╫\003\n\017\032\r\n\vjAl2vgAAAAE\022\t\bµû≥╩\220╠≈\002\030┐╬╜\217Ä╠≈\002\"≈\001\n*\n\027\n\025\061\061\063\061\062\062\065\065\061\070\064\071\070\065\062\060\070\060\065\063\061\022\017\032\r\n\vjAl2vgAAAAE\020┐╬╜\217Ä╠≈\002 "
        decoded_response = 0x7bac018 "\022\fCPmUsIa77PcC\032\t\bƒ▓\200Ü▒σ≈\002\"╫\003\n\017\032\r\n\vjAl2vgAAAAE\022\t\bµû≥╩\220╠≈\002\030┐╬╜\217Ä╠≈\002\"≈\001\n*\n\027\n\025\061\061\063\061\062\062\065\065\061\070\064\071\070\065\062\060\070\060\065\063\061\022\017\032\r\n\vjAl2vgAAAAE\020┐╬╜\217Ä╠≈\002 "
        response_len = 7209
        content_type = 0x4bdb990 "application/vnd.google.octet-stream-compressible"
#14 0x0386e5da in purple_http_connection_terminate (hc=0x4bda718)
    at purple2compat/http.c:1729
        __PRETTY_FUNCTION__ = "purple_http_connection_terminate"
#15 0x0386d6c2 in _purple_http_recv_loopbody (hc=0x4bda718, fd=1576)
    at purple2compat/http.c:1297
        redirect = 0x0
        len = 5
        buf = "0\r\n\r\n001\r\n\003\r\n00000001\r\n\000\r\n00000001\r\nP\r\n00000001\r\n\004\r\n01\r\nn\r\n5\r\nb)\034\000\000\r\n\r╙YÆ{>≡ε∙\000°▀\000\000\000  \r\n¿8\006F\032$\n\000\062å*F\220\036HHfeΣ M╦╚A3í╒7\032`\026F\027MF/┐8º`╞ΦΩ\033>\023√(^v╜}▒▐\230Q\177∩ªgd3!Z:âæU─\031δ*X▓⌠∩O-{.\032¡\\\230òΣ¢}╘D·╬/╖\215{\231d┐▀▀┤■½â'\004w└\022Æ\020"...
        got_anything = 1
#16 0x0386d6ed in _purple_http_recv (_hc=0x4bda718, fd=1576,
    cond=PURPLE_INPUT_READ) at purple2compat/http.c:1308
        hc = 0x4bda718
#17 0x6d634bed in ?? () from C:\Program Files (x86)\Pidgin\pidgin.dll
No symbol table info available.
#18 0x685eb167 in g_main_context_dispatch ()
   from C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll
No symbol table info available.
#19 0x685eb90d in g_main_context_iterate.clone ()
   from C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll
No symbol table info available.
#20 0x685ebd9d in g_main_loop_run ()
   from C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll
No symbol table info available.
#21 0x61854260 in gtk_main ()
   from C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll
No symbol table info available.
#22 0x6d653ffd in ?? () from C:\Program Files (x86)\Pidgin\pidgin.dll
No symbol table info available.
#23 0x00b42881 in ?? ()
No symbol table info available.
#24 0x00b49c7d in ?? ()
No symbol table info available.
#25 0x00b41386 in ?? ()
No symbol table info available.
#26 0x7639fa29 in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\SysWOW64\kernel32.dll
No symbol table info available.
#27 0x77267a7e in ntdll!RtlGetAppContainerNamedObjectPath ()
   from C:\Windows\SysWOW64\ntdll.dll
No symbol table info available.
#28 0x77267a4e in ntdll!RtlGetAppContainerNamedObjectPath ()
   from C:\Windows\SysWOW64\ntdll.dll
No symbol table info available.
#29 0x00000000 in ?? ()
No symbol table info available.
```

**Comment by nxths** [comment]
Not seeing crashes anymore after wiping/reinstalling pidgin and downloading the latest .dll files for this plugin.  Unclear what fixed it, but works for me now.
